### PR TITLE
Add new function to calculate raw/unexpanded composition data

### PR DESCRIPTION
**Pull request by chantelwetzel-noaa**
This pull request includes:

1. A new function to process raw/unexpanded composition data for either marginal lengths or ages.  This function will ideally replace the `UnexpandedLFs.fn` and `UnexpandedLFs.fn` functions.  This pull request leaves these existing functions as is with the current plan to deprecate them once individuals have switched to this newer function.  Having some overlap between the two also allows some time to ensure that the new function works as needed in all situations.  Additionally, functionality has been incorporated that can allow users to apply this function to other data sets as long as specific columns are present.
2. Added new tests for the `get_raw_comps` function. 
3.  The default `printfolder` function argument has been updated to be `forSS3` to align with the current abbreviation for Stock Synthesis. This is updated in all functions that include this argument and a template for this parameter was created to ensure documentation consistency across functions.
4.  Adds example usage of the `get_raw_comps` function in the vignette for users.

Items that would be useful to get a review of the `get_raw_comps` function are the clarity of documentation, functionality (e.g., is returning a list okay), adequacy of new tests, and whether the function name is clear.

### CODE REVIEW

**Comment by iantaylor-NOAA** [comment]
@chantelwetzel-noaa, thanks for adding this new function. On first glance it looks great, but I'd like to try it out and read the code and documentation in more detail. I hope to have time to do that tomorrow.

**Review by iantaylor-NOAA — APPROVED** [review]
Looks great. 
Thanks for making this happen @chantelwetzel-noaa!

I pushed a few typo fixes and only have two suggestions inspired by looking through the code and running the examples in the vignette and the help page.

First, `plot_comps()` is great, but it would be nice if it worked with the output from `get_raw_comps()`. That is, it would be great to run `length_comps <- get_raw_comps(...)` followed by `plot_comps(data = length_comps$sexed)`, or even `plot_comps(data = length_comps)`, but currently `plot_comps()` expects the old column headers like "InputN" and "ageErr".

Second, my preference for the unsexed data frame if `two_sex_comps` is TRUE would be to report 0 values for the male columns rather than repeat the matrix of unsexed fish proportions in the female and male columns. This would probably be as simple as changing line 218 from
`out_u <- cbind(tmp, Results[, -c(1:2)], Results[, -c(1:2)])`
to
`out_u <- cbind(tmp, Results[, -c(1:2)], 0 * Results[, -c(1:2)])`
although it could also be applied to other functions that make tables of unsexed fish.
Similarly, in the code that creates the CAAL data, my preference would be to have the female CAAL data only appear in the first set of columns and the male data only in the second set with 0 for the other sex in both cases rather than repeating. None of this makes a difference for SS3, but I think it would make more clear to the user which values are actually being read by the model. Those changes are all outside the scope of this PR, so feel free to ignore the suggestion or deal with it later.

**Comment by chantelwetzel-noaa** [comment]
Thanks @iantaylor-NOAA.  Thank you for catching the typos and the instances where I did not fully change the printfolder.   Also, good catch about `plot_comps` not working with the output.  It did work with the initial version of this new function but I modified the column names at the last stage of working on this to something more standard in terms of case and separators.  I will do modifications next week to get this function to work with `plot_comps` after I think about reverting the column names or modifying the other composition functions to use these new column names.  Currently, I am leaning toward the latter approach but will think about it.

**Comment by iantaylor-NOAA** [comment]
One of the tests temporarily failed and then fixed itself (seems like maybe `pull_biological_samples()` timed out due to some network issue, but only on Ubuntu), but looking into inspired me to remove a warning in the tests about a deprecated function by adding one more commit to this PR in e9563ae.

**Comment by iantaylor-NOAA** [comment]
I like the new column names.
You could add something at the top of `plot_comps()` to just automatically convert the old ones instead of modifying all the other functions that create them.

**Comment by iantaylor-NOAA** [comment]
Thanks @chantelwetzel-noaa for making all the changes on my wishlist.

**Pull request merged**
