### PR TITLE
fix(pull_catch): Allow a vector of common or latin

### PR DESCRIPTION
**Pull request by kellijohnson-NOAA**
the if statement was failing for the case when the latin or common name input arguments were a vector rather than a single character string because, for example,
common_name = c("sablefish", "longnose skate") would return FALSE FALSE in the if statement because it was checking species and not species[1] because logically if a user wants all species the vector species will just be one entry and thus the check for species[1] is okay.

### CODE REVIEW

**Comment by kellijohnson-NOAA** [comment]
@chantelwetzel-noaa sorry to make you review this when  you are so busy but I am super hesitant to just push to main right now when everyone is depending on this package working. This should be an easy review though.

**Review by chantelwetzel-noaa — COMMENTED** [review]
I just tested this and it works just fine and I see that the `pull_bio` function uses this same approach.  My only question is whether we want to do anything about this warning that is generated with species has a length > 1: 

`
Warning message:
In if (species == "pull all") { :
  the condition has length > 1 and only the first element will be used
`
It works fine but wanted to make sure this was noted in case you had any concerns about this warning even though it does not impact how the function works.

**Comment by kellijohnson-NOAA** [comment]
Thanks Chantel. This is a good reminder why I should do a pull request 😆 

I searched for all `species[1] == "pull all"` and changed them to `any(species == "pull all")` *BUT* I am getting something wrong in the results because they do not match between `pull_catch()` and `PullCatch.fn()` nor do they match in dimension if I pull each species one at a time with `pull_catch()`. For example, if I am pulling sablefish and longnose skate I get
```
new <- pull_catch(common_name = c("longnose skate","sablefish"),survey="NWFSC.Combo")
test <- PullCatch.fn(Name = c("sablefish","longnose skate"),SurveyName="NWFSC.Combo")
dim(test);dim(new)                                          ")
[1] 24060    18
[1] 48120    22
> all(table(test$Year)*2==table(new$Year))
[1] TRUE
```
I cannot test what I would get with the package as is using `pull_catch()` because instead of a warning message like in `pull_bio()` it is an error message that kills the function. I think maybe it has to do with the expand.grid option on line 210 but I am not sure. I can look into this more but I just wanted to see if you had any ideas.

**Comment by chantelwetzel-noaa** [comment]
@kellijohnson-NOAA Can you review the changes in this pull request?  My recent commits do the following:

1. Fix how data was returned for the Triennial and AFSC.Slope surveys in pull_bio()
2. Deprecates PullCatch.fn(), PullBio.fn(), and PullHaul.fn() where the newer functions are used internally allowing backward compatibility.
3. Add a pull_spp() that does the same thing as the PullSpp.fn(). Once this is confirmed we could deprecate the PullSpp.fn() similar to the other Pull functions.
4. Update the tests based on changes in the data warehouse. 
5. Update documentation accordingly. 
6. Add a new package tag

**Comment by kellijohnson-NOAA** [comment]
@chantelwetzel-noaa I am happy to review this but what is the desired turn-around time? Would next week be sufficient?

**Comment by chantelwetzel-noaa** [comment]
Next week would be fine.  Thank you!

**Comment by kellijohnson-NOAA** [comment]
I think I figured out the code needed to replace lines 191--218

```
  # Group positive_tows by common_name and scientific_name
  positive_tows_grouped <- dplyr::group_by(
    .data = positive_tows,
    common_name, scientific_name
  )
  # Split positive_tows into 1 data frame for each combination of common_name
  # and scientific_name and store in a named list for purrr::map()
  positive_tows_split <- dplyr::group_split(positive_tows_grouped)
  group_names <- dplyr::group_keys(positive_tows_grouped)
  names(positive_tows_split) <- tidyr::unite(group_names, col = "groups") |>
    dplyr::pull(groups)
 
 # For each data frame in the large list, find the tows that are not present
  # in positive_tows and join them into a single data frame
  # Give them the appropriate common and scientific names using .id then split
  # the concatenated column out into the two original columns
  names_intersect <- intersect(colnames(all_tows), colnames(positive_tows))
  zero_tows <- purrr::map_df(
    .x = positive_tows_split,
    .f = \(y) dplyr::anti_join(x = all_tows, y = y, by = names_intersect),
    .id = "groups"
  ) |>
    tidyr::separate_wider_delim(
      cols = "groups",
      delim = "_",
      names = colnames(group_names)
    )

  # Join the positive tows with the tow information
  positive_tows_with_tow_info <- dplyr::left_join(
    x = positive_tows,
    y = all_tows,
    by = intersect(colnames(all_tows), colnames(positive_tows))
  )
  # Join the augmented positive tow information with the zero tows
  # arrange by common_name and tow_id
  catch <- dplyr::full_join(
    x = positive_tows_with_tow_info,
    y = zero_tows,
    by = c(colnames(group_names), colnames(all_tows))
  ) |>
    dplyr::arrange(common_name, trawl_id)
```

Let me know if you want me to push this or if you want to add it, potentially with some more comments 😄! One thing to note is that the column order of `catch` is different than what it was before. I personally do not think that it matters but it could for some people if they use `data[, 1]` instead of `data[, "tow_id"] in their downstream code. Last, I have not formally tested this code so some tests might break if the previous matters. I just wanted to at least check in with you if the proposed code makes sense before testing it.

A side note ... the example that I am working with has lingcod and sablefish and there is a row in `positive_tows` that has NA values, i.e.,
```
dplyr::filter(positive_tows, is.na(total_catch_numbers))
  common_name    scientific_name                                       project
1   sablefish Anoplopoma fimbria Groundfish Slope and Shelf Combination Survey
  year    vessel tow total_catch_numbers total_catch_wt_kg subsample_count
1 2017 Excalibur  96                  NA               4.6              NA
  subsample_wt_kg cpue_kg_per_ha_der
1             4.6           3.347159
```
should this be concerning? I figured that the replace NA call later was only dealing with zero tows but this proves that wrong.

**Comment by chantelwetzel-noaa** [comment]
Yeesh!  When I asked you to look at how to remove the loop in the code, I thought it would be a quick 3-4 line change with a clever dplyr call.  Sorry that this task ended up being a bit more than that.  I will take the code you have proposed, add it locally, test it out, add additional comments for myself if needed, and then push once I am done.  Thank you for doing this.

**Comment by kellijohnson-NOAA** [comment]
No problem @chantelwetzel-noaa. One thing to note, is that the scientific_name column is now populated for the zero tows, which I think is a nice feature in the returned product. Let me know if you want to chat about how I got that done.

**Comment by chantelwetzel-noaa** [comment]
@kellijohnson-NOAA I think all the revisions that we made here now have the pull functions working correctly across the various data pull options.  Can you please look over the most recent changes and let me know if you see anything additional that should be investigated?  Thanks

**Comment by kellijohnson-NOAA** [comment]
`pull_catch()` fails if no survey name is supplied without a warning message telling people the exact reason why
```
> dat_lingcod_anoplopoma <- pull_catch(
+     common_name = "lingcod"
+   )
Error in if (survey %in% c("NWFSC.Shelf.Rockfish", "NWFSC.Hook.Line")) { :
  argument is of length zero
```
Users should be able to keep the default value if there is one, and if they are mandated to supply an entry then it should be missing rather than `NULL`. How come it is `NULL`? If it was missing, then the user would get a more informative error message by default without us having to write one.

**Comment by kellijohnson-NOAA** [comment]
The test that I just pushed that pulls 2017 for lingcod and sablefish two different ways should have worked but is failing.
```
Error: NROW(dat_lingcod_sablefish) not equal to NROW(dat_lingcod_anoplopoma).
1/1 mismatches
[1] 1410 - 705 == 705
```
which leads me to believe that the non-zero tows for the combination of common name and scientific name is not working.

**Comment by chantelwetzel-noaa** [comment]
This is a weird combination that I have not considered people trying but someone could try.  The code pulls either the scientific names or the common names provided not a combination of the two.  I think the easiest fix to this is to add a check and force people to use one or the other when requesting multiple species.  What do you think about that?

**Comment by kellijohnson-NOAA** [comment]
@chantelwetzel-noaa I think that your proposal is the best option of all that I thought about because it would be a pretty big lift to allow for both, which I think should be done in a separate issue/pull request if you want to allow for that behavior.

**Pull request merged**
