### PR TITLE
add survey name associated with samples in Canada

### PR DESCRIPTION
**Pull request by iantaylor-NOAA**
very simple change

### CODE REVIEW

**Comment by chantelwetzel-noaa** [comment]
Can you provide me a one sentence description for each of these survey names and how they are different?

**Comment by iantaylor-NOAA** [comment]
I think we would need help from @Curt-Whitmire-NOAA or others on the database side of things to describe each survey and understand the differences between them. It looks like the status-quo list of survey names that are currently in `createMatrix.fn()` were previously in PullBio.fn() when you created it in 2018 with this commit: https://github.com/pfmc-assessments/nwfscSurvey/commit/8e5ce6492de871b40384ca6b2c593ab76a3d4416 before moving them to a separate file later. 

I discovered that the triennial samples from Canada were associated with a different survey name by seeing that they were present in the map view of the data warehouse at https://www.webapps.nwfsc.noaa.gov/data/map and then downloading a CSV file of specimins such as [TrawlSpecimens (2).csv](https://github.com/pfmc-assessments/nwfscSurvey/files/11045459/TrawlSpecimens.2.csv) for petrale from 1989, where the "project" column contains both "Groundfish Triennial Shelf Survey" and "Triennial Shelf Groundfish Survey: Canada".

I don't think there's any harm in having a longer list of surveys since I don't think anyone would accidentally pull data from survey names that they are not familiar with. The benefit of making the Canadian samples accessible is for our colleagues at DFO to be able to use the main branch of this package to get samples from their waters.

**Comment by chantelwetzel-noaa** [comment]
The newer [documentation](https://github.com/pfmc-assessments/nwfscSurvey/blob/main/man-roxygen/survey.R) associated with the `pull_bio` and `pull_catch` functions have more information about each survey. It would be useful to provide information to users of how these two survey names are different.

**Comment by iantaylor-NOAA** [comment]
Sorry @chantelwetzel-noaa, having recently edited `man-roxygen/survey.R`, I should have remembered that it would need an update. I have added a description of the new `Triennial.Canada` entry associated with this Pull Request. There are still some other surveys on the list which are not described but I am not the best person to fill in those gaps and they seem a low priority.

**Comment by Curt-Whitmire-NOAA** [comment]
A little late to the party, but a list of valid Project values can be found [here](https://www.webapps.nwfsc.noaa.gov/data/metadata/warehouse.operation_dim), by searching for "project".
The current listed values are:

1. Groundfish Shelf Survey
2. Groundfish Slope and Shelf Combination Survey
3. Groundfish Slope Survey
4. Groundfish Triennial Shelf Survey
5. Hypoxia Study
6. Santa Barbara Basin Study
7. Shelf Rockfish [2004-2015] (*will soon update to as the data go through 2018)
8. Video Study

@iantaylor-NOAA is correct that the Canadian records from the Triennial surveys are further designated with "Canada" in the name, as in "**Triennial Shelf Groundfish Survey: Canada**". These records span years 1980-2001 whereas the U.S. triennial survey spans years 1977-2004.

Also, Slope Survey records conducted by AFSC/RACE fall under the following project name - **AFSC/RACE Slope Survey** - and span years 1984-2001.

**Comment by Curt-Whitmire-NOAA** [comment]
@chantelwetzel-noaa @iantaylor-NOAA  if it would be helpful, I can add the specific project_name value for the Canadian Triennial records to the Data Warehouse metadata page. I don't know how this affects your documentation for the data pulls, so let me know if you'd like me to stand down so as not to confuse folks.

**Pull request merged**
